name: GitHub Metrics
on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # ğŸ§© Base layout
          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_timezone: Asia/Kolkata
          theme: dark

          # ğŸ“Š Coding habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # ğŸ—“ Contribution calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # ğŸ§  Languages
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          # ğŸ”¥ Streaks
          plugin_streak: yes

          # ğŸ§© Repositories
          plugin_repositories: yes
          plugin_repositories_featured: ""
